import React from 'react'
import StockDetails from './components/StockDetails'
import OHLCVChart from './components/OHLCVChart'

function ViewCompany() {
    const stockDetails = {
        "Symbol": "IBM",
        "AssetType": "Common Stock",
        "Name": "International Business Machines",
        "Description": "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
        "CIK": "51143",
        "Exchange": "NYSE",
        "Currency": "USD",
        "Country": "USA",
        "Sector": "TECHNOLOGY",
        "Industry": "COMPUTER & OFFICE EQUIPMENT",
        "Address": "1 NEW ORCHARD ROAD, ARMONK, NY, US",
        "FiscalYearEnd": "December",
        "LatestQuarter": "2023-12-31",
        "MarketCapitalization": "175061631000",
        "EBITDA": "14291000000",
        "PERatio": "23.43",
        "PEGRatio": "4.404",
        "BookValue": "24.63",
        "DividendPerShare": "6.63",
        "DividendYield": "0.0348",
        "EPS": "8.15",
        "RevenuePerShareTTM": "67.89",
        "ProfitMargin": "0.121",
        "OperatingMarginTTM": "0.232",
        "ReturnOnAssetsTTM": "0.0471",
        "ReturnOnEquityTTM": "0.337",
        "RevenueTTM": "61860000000",
        "GrossProfitTTM": "32688000000",
        "DilutedEPSTTM": "8.15",
        "QuarterlyEarningsGrowthYOY": "0.2",
        "QuarterlyRevenueGrowthYOY": "0.041",
        "AnalystTargetPrice": "188.24",
        "AnalystRatingStrongBuy": "4",
        "AnalystRatingBuy": "4",
        "AnalystRatingHold": "10",
        "AnalystRatingSell": "3",
        "AnalystRatingStrongSell": "0",
        "TrailingPE": "23.43",
        "ForwardPE": "18.98",
        "PriceToSalesRatioTTM": "2.83",
        "PriceToBookRatio": "7.77",
        "EVToRevenue": "3.582",
        "EVToEBITDA": "15.08",
        "Beta": "0.708",
        "52WeekHigh": "199.18",
        "52WeekLow": "116.36",
        "50DayMovingAverage": "186.86",
        "200DayMovingAverage": "156.78",
        "SharesOutstanding": "916745000",
        "DividendDate": "2024-03-09",
        "ExDividendDate": "2024-02-08"
    };
    const ohlcvData = [
        {
            "timestamp": "2024-03-28 19:55:00",
            "open": "190.9500",
            "high": "190.9500",
            "low": "190.4000",
            "close": "190.4100",
            "volume": "91"
        },
        {
            "timestamp": "2024-03-28 19:50:00",
            "1. open": "190.2000",
            "2. high": "190.2100",
            "3. low": "190.2000",
            "4. close": "190.2100",
            "5. volume": "3"
        },
        {
            "timestamp": "2024-03-28 19:30:00",
            "1. open": "190.2000",
            "2. high": "190.2000",
            "3. low": "190.2000",
            "4. close": "190.2000",
            "5. volume": "16"
        },
        {
            "timestamp": "2024-03-28 19:10:00",
            "1. open": "190.1600",
            "2. high": "190.1600",
            "3. low": "190.1600",
            "4. close": "190.1600",
            "5. volume": "0"
        },
        {
            "timestamp": "2024-03-28 19:00:00",
            "1. open": "190.9600",
            "2. high": "190.9600",
            "3. low": "190.9500",
            "4. close": "190.9500",
            "5. volume": "941332"
        },
        {
            "timestamp": "2024-03-28 18:55:00",
            "1. open": "191.2190",
            "2. high": "191.2190",
            "3. low": "191.0600",
            "4. close": "191.0600",
            "5. volume": "1"
        }
    ];

    return (
        <div className='flex'> 
            <StockDetails stock={stockDetails} />
            <OHLCVChart ohlcvData={ohlcvData} />
        </div>
    )
}

export default ViewCompany